//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LangerSalesOrdersWebsite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TextResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TextResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LangerSalesOrdersWebsite.Resources.TextResources", typeof(TextResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account #.
        /// </summary>
        public static string Label_AccountNumber {
            get {
                return ResourceManager.GetString("Label_AccountNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        public static string Label_DueDate {
            get {
                return ResourceManager.GetString("Label_DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freight Amount.
        /// </summary>
        public static string Label_FreightAmount {
            get {
                return ResourceManager.GetString("Label_FreightAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Date.
        /// </summary>
        public static string Label_OrderDate {
            get {
                return ResourceManager.GetString("Label_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order #.
        /// </summary>
        public static string Label_PurchaseOrderNumber {
            get {
                return ResourceManager.GetString("Label_PurchaseOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Order #.
        /// </summary>
        public static string Label_SalesOrderNumber {
            get {
                return ResourceManager.GetString("Label_SalesOrderNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salesperson.
        /// </summary>
        public static string Label_SalesPersonName {
            get {
                return ResourceManager.GetString("Label_SalesPersonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship Date.
        /// </summary>
        public static string Label_ShipDate {
            get {
                return ResourceManager.GetString("Label_ShipDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Label_Status {
            get {
                return ResourceManager.GetString("Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal Amount.
        /// </summary>
        public static string Label_SubtotalAmount {
            get {
                return ResourceManager.GetString("Label_SubtotalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Amount.
        /// </summary>
        public static string Label_TaxAmount {
            get {
                return ResourceManager.GetString("Label_TaxAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Due.
        /// </summary>
        public static string Label_TotalAmountDue {
            get {
                return ResourceManager.GetString("Label_TotalAmountDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Orders.
        /// </summary>
        public static string Title_SalesOrderList {
            get {
                return ResourceManager.GetString("Title_SalesOrderList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Langer Web Exercise.
        /// </summary>
        public static string Title_WebApp {
            get {
                return ResourceManager.GetString("Title_WebApp", resourceCulture);
            }
        }
    }
}
